# Configuration for pre-commit hooks (see https://pre-commit.com/).

exclude: ^(dbt_common/events/types_pb2.py)

# Force all unspecified python hooks to run python 3.8
default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude_types:
      - "markdown"
  - id: check-case-conflict
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    # N.B.: Mypy is... a bit fragile.
    #
    # By using `language: system` we run this hook in the local
    # environment instead of a pre-commit isolated one.  This is needed
    # to ensure mypy correctly parses the project.

    # It may cause trouble
    # in that it adds environmental variables out of our control to the
    # mix.  Unfortunately, there's nothing we can do about per pre-commit's
    # author.
    # See https://github.com/pre-commit/pre-commit/issues/730 for details.
    args: [--show-error-codes]
    files: ^dbt_common/
    language: system
  - id: mypy
    alias: mypy-check
    stages: [manual]
    args: [--show-error-codes, --pretty]
    files: ^dbt_common
    language: system
