# Configuration for pre-commit hooks (see https://pre-commit.com/).

exclude: ^(dbt_common/events/types_pb2.py)

# Force all unspecified python hooks to run python 3.8
default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: debug-statements
  - id: check-yaml
    args: [--unsafe]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude_types:
      - "markdown"
  - id: check-case-conflict
  # - id: format
  #   name: format
  #   entry: hatch run lint-all
  #   language: system
  #   types: [python]
  #   pass_filenames: false
  #   verbose: true