ignore:
  - ".github"
  - ".changes"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1% # Reduce noise by ignoring rounding errors in coverage drops
    patch:
      default:
        target: auto
        threshold: 80%
