from .exceptions import (
    JsonSchemaDefinitionException as JsonSchemaDefinitionException,
    JsonSchemaException as JsonSchemaException,
    JsonSchemaValueException as JsonSchemaValueException,
)
from .version import VERSION as VERSION

def validate(
    definition, data, handlers=..., formats=..., use_default: bool = ..., use_formats: bool = ...
): ...
def compile(
    definition, handlers=..., formats=..., use_default: bool = ..., use_formats: bool = ...
): ...
def compile_to_code(
    definition, handlers=..., formats=..., use_default: bool = ..., use_formats: bool = ...
): ...
