name: Setup Python env
description: Install Python & Hatch
inputs:
    python-version:
      description: 'Version of Python to Install'
      required: true
      default: '3.9'
runs:
  using: "composite"
  steps:
  - name: "Set up Python ${{ inputs.python-version }}"
    uses: actions/setup-python@v4
    with:
      python-version: "${{ inputs.python-version }}"

  - name: Install Hatch
    shell: bash
    run: |
      python -m pip install --user --upgrade pip
      python -m pip install hatch
