name: Setup Python env
description: Install Python & Hatch
inputs:
    python-version:
      description: 'Version of Python to Install'
      required: true
      default: '3.10'
runs:
  using: "composite"
  steps:
  - name: "Set up Python ${{ inputs.python-version }}"
    uses: actions/setup-python@v4
    with:
      python-version: "${{ inputs.python-version }}"

  - name: "Install hatch"
    uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # pypa/hatch@install
